/*
Little MUS Player v0.3 — C# port

Copyright 2025 Andrew Towers
Ported from https://github.com/raffecat/LittleMUS

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

This file retains the LittleMUS sequencing, GENMIDI voice allocation, OPL
register mapping, attenuation, panning, pitch bend, and software LFO logic.
*/

using System;

namespace Doom.Audio
{
    /// <summary>
    /// Allocation-free-after-warmup MUS sequencer driving an OPL3 device at 140 Hz.
    /// The chip is rendered at the requested output rate; this uses fractional 140 Hz
    /// scheduling instead of LittleMUS's native 49,716 Hz / 355-sample cadence.
    /// </summary>
    public sealed class MusOplPlayer
    {
        public const int TickRate = 140;
        public const int VoiceCount = 18;

        private const int KeyOn = 1 << 13;
        private const int KeyOffMask = ~KeyOn;
        private const int CentrePan = 0x30;
        private const int LeftPan = 0x10;
        private const int RightPan = 0x20;
        private const int CentreAttenuation = 6;
        private const int PanThreshold = 21;
        private const int LastPlayableNote = 95;

        private static readonly int[] Operator1 = { 0, 1, 2, 8, 9, 10, 16, 17, 18 };
        private static readonly int[] Operator2 = { 3, 4, 5, 11, 12, 13, 19, 20, 21 };

        // Generated by LittleMUS note_freq.py.
        private static readonly ushort[] NoteCommands =
        {
            8536, 8557, 8579, 8602, 8626, 8652, 8679, 8708, 8739, 8772, 8806, 8843,
            8881, 8922, 8966, 9012, 9061, 9112, 9167, 9732, 9763, 9796, 9830, 9867,
            9905, 9946, 9990, 10036, 10085, 10136, 10191, 10756, 10787, 10820, 10854,
            10891, 10929, 10970, 11014, 11060, 11109, 11160, 11215, 11780, 11811,
            11844, 11878, 11915, 11953, 11994, 12038, 12084, 12133, 12184, 12239,
            12804, 12835, 12868, 12902, 12939, 12977, 13018, 13062, 13108, 13157,
            13208, 13263, 13828, 13859, 13892, 13926, 13963, 14001, 14042, 14086,
            14132, 14181, 14232, 14287, 14852, 14883, 14916, 14950, 14987, 15025,
            15066, 15110, 15156, 15205, 15256, 15311, 15876, 15907, 15940, 15974,
            16011, 16049, 16090, 16134, 16180, 16229, 16280, 16335,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        };

        // Generated by LittleMUS vol_ramp.py.
        private static readonly sbyte[] AttLogSquare =
        {
            96,96,90,81,74,69,65,61,58,55,53,51,49,47,45,43,42,41,39,38,37,36,35,34,
            33,32,31,30,29,28,27,27,26,25,24,24,23,23,22,21,21,20,20,19,19,18,17,17,
            17,16,16,15,15,14,14,13,13,13,12,12,11,11,11,10,10,9,9,9,8,8,8,7,7,7,
            6,6,6,6,5,5,5,4,4,4,4,3,3,3,2,2,2,2,1,1,1,1,0,0,0,0,0,0,0,0,-1,-1,
            -1,-1,-1,-2,-2,-2,-2,-3,-3,-3,-3,-3,-4,-4,-4,-4,-4,-4,-5,-5,-5,-5
        };

        // Generated by LittleMUS lfo.py, 8 depths × 12 steps.
        private static readonly sbyte[] LfoTable =
        {
            0, 0, 1, 2, 1, 0, 0, 0, -1, -2, -1, -1,
            0, 1, 3, 4, 3, 1, 0, -1, -3, -4, -3, -2,
            0, 2, 5, 6, 5, 2, 0, -2, -5, -6, -5, -3,
            0, 3, 6, 8, 6, 3, 0, -3, -6, -8, -6, -4,
            0, 4, 8, 10, 8, 4, 0, -4, -8, -10, -8, -5,
            0, 5, 10, 12, 10, 5, 0, -5, -10, -12, -10, -6,
            0, 6, 12, 14, 12, 6, 0, -6, -12, -14, -12, -7,
            0, 7, 13, 16, 13, 7, 0, -7, -13, -16, -13, -8,
        };

        private readonly IOplChip _chip;
        private readonly GenMidiBank _bank;
        private readonly Channel[] _channels = new Channel[16];
        private readonly HardwareVoice[] _voices = new HardwareVoice[VoiceCount];
        private readonly int _sampleRate;
        private readonly double _samplesPerTick;

        private MusSong _song;
        private bool _loop;
        private bool _playing;
        private int _eventIndex;
        private int _delay;
        private uint _musTime;
        private uint _nextSequence;
        private int _lfoOffset;
        private int _mainAttenuation;
        private double _framesUntilTick;

        public MusOplPlayer(MusSong song, GenMidiBank bank, IOplChip chip, int sampleRate = 44100)
        {
            _song = song ?? throw new ArgumentNullException(nameof(song));
            _bank = bank ?? throw new ArgumentNullException(nameof(bank));
            _chip = chip ?? throw new ArgumentNullException(nameof(chip));
            if (sampleRate <= 0) throw new ArgumentOutOfRangeException(nameof(sampleRate));
            _sampleRate = sampleRate;
            _samplesPerTick = sampleRate / (double)TickRate;
            for (int i = 0; i < _channels.Length; i++) _channels[i] = new Channel();
            for (int i = 0; i < _voices.Length; i++) _voices[i] = new HardwareVoice();
            SetVolume(100);
        }

        public bool IsPlaying => _playing;
        public int SampleRate => _sampleRate;

        public void Start(bool loop)
        {
            _loop = loop;
            _playing = true;
            _eventIndex = 0;
            _delay = 0;
            _musTime = 0;
            _nextSequence = 0;
            _lfoOffset = 0;
            _framesUntilTick = 0;
            _chip.Reset(_sampleRate);
            ResetSequencerState();
            InitializeChip();
        }

        public void Stop()
        {
            if (!_playing) return;
            _chip.WriteRegister(0xBD, 0);
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice voice = _voices[i];
                if (voice.InstrumentSelector >= 0)
                {
                    GenMidiVoice instrumentVoice = VoiceFor(voice.InstrumentSelector);
                    int bank = i >= 9 ? 0x100 : 0;
                    int channel = i % 9;
                    if ((instrumentVoice.CarSustain & 15) < 4)
                        _chip.WriteRegister(bank | 0x80 | Operator2[channel],
                            (byte)((instrumentVoice.CarSustain & 0xF0) | 4));
                    if ((voice.Feedback & 1) != 0 && (instrumentVoice.ModSustain & 15) < 4)
                        _chip.WriteRegister(bank | 0x80 | Operator1[channel],
                            (byte)((instrumentVoice.ModSustain & 0xF0) | 4));
                }
                KeyOffHardware(i);
            }
            _playing = false;
        }

        public void SetVolume(int volume)
        {
            _mainAttenuation = AttLogSquare[Clamp(volume, 0, 127)];
        }

        /// <summary>Advances one MUS tick, returning false once a non-looping song ends.</summary>
        public bool Tick()
        {
            if (!_playing) return false;
            if (_delay > 1)
            {
                _delay--;
                _musTime++;
                DoLfo();
                return true;
            }

            _musTime++;
            int guard = 0;
            while (_playing && guard++ < 4096)
            {
                if (_eventIndex >= _song.Events.Length)
                {
                    EndScore();
                    break;
                }

                MusEvent e = _song.Events[_eventIndex++];
                if (e.Type == MusEventType.ScoreEnd)
                {
                    EndScore();
                    break;
                }

                Execute(e);
                if (e.DelayTicks > 0)
                {
                    _delay = e.DelayTicks;
                    break;
                }
            }
            DoLfo();
            return _playing;
        }

        /// <summary>Renders frames, invoking MUS ticks at a fractional 140 Hz cadence.</summary>
        public void Render(float[] stereoInterleaved, int sampleCount)
        {
            if (stereoInterleaved == null) throw new ArgumentNullException(nameof(stereoInterleaved));
            if (sampleCount < 0 || stereoInterleaved.Length < sampleCount * 2)
                throw new ArgumentOutOfRangeException(nameof(sampleCount));

            int offset = 0;
            while (offset < sampleCount)
            {
                if (_framesUntilTick <= 0)
                {
                    Tick();
                    _framesUntilTick += _samplesPerTick;
                }
                int frames = (int)Math.Ceiling(_framesUntilTick);
                if (frames < 1) frames = 1;
                if (frames > sampleCount - offset) frames = sampleCount - offset;
                _chip.Render(stereoInterleaved, offset, frames);
                offset += frames;
                _framesUntilTick -= frames;
            }
        }

        private void EndScore()
        {
            if (_loop)
            {
                // Unlike the original pointer-only loop, reset the emulated device so a
                // Unity audio callback cannot retain envelopes from the prior iteration.
                Start(true);
            }
            else
            {
                for (int i = 0; i < VoiceCount; i++) KeyOffHardware(i);
                _playing = false;
            }
        }

        private void Execute(MusEvent e)
        {
            Channel channel = _channels[e.Channel];
            switch (e.Type)
            {
                case MusEventType.Release: KeyOffNote(e.Channel, e.Data1); break;
                case MusEventType.Play:
                    PlayNote(e.Channel, e.Data1, e.Data2, e.HasExplicitVolume || e.Data2 != 0, channel);
                    break;
                case MusEventType.Pitch:
                    channel.Bend = e.Data1 - 128;
                    BendChannel(e.Channel, channel.Bend);
                    break;
                case MusEventType.System: Controller(e.Channel, e.Data1, 0); break;
                case MusEventType.Controller:
                    if (e.Data1 < 10) Controller(e.Channel, e.Data1, e.Data2);
                    break;
            }
        }

        private void PlayNote(int musChannel, int note, int suppliedVolume, bool hasExplicitVolume, Channel channel)
        {
            int volume = hasExplicitVolume ? suppliedVolume : channel.LastVolume;
            if (hasExplicitVolume) channel.LastVolume = (byte)suppliedVolume;
            if (channel.Mono) KeyOffChannel(musChannel);
            int noteAtt = AttLogSquare[Clamp(volume, 0, 127)];
            int channelAtt = channel.VolumeAttenuation;

            if (musChannel == 15)
            {
                if (note < 35 || note > 81) return;
                GenMidiInstrument instrument = _bank.Percussion(note);
                int selector = 128 + note - 35;
                PlayInstrument(selector, note, instrument.FixedNote, 0, noteAtt, channelAtt, musChannel, channel);
                if (instrument.IsDoubleVoice)
                    PlayInstrument(selector | 0x100, note | 0x100, instrument.FixedNote, 0,
                        noteAtt, channelAtt, musChannel, channel);
                return;
            }

            GenMidiInstrument melodic = _bank.Melodic(channel.InstrumentIndex);
            int baseNote = melodic.IsFixedPitch ? melodic.FixedNote : note;
            int offset0 = melodic.IsFixedPitch ? 0 : melodic.Voice0.BaseNoteOffset;
            PlayInstrument(channel.InstrumentIndex, note, baseNote, offset0, noteAtt, channelAtt, musChannel, channel);
            if (melodic.IsDoubleVoice)
                PlayInstrument(channel.InstrumentIndex | 0x100, note | 0x100, baseNote,
                    melodic.IsFixedPitch ? 0 : melodic.Voice1.BaseNoteOffset,
                    noteAtt, channelAtt, musChannel, channel);
        }

        private void PlayInstrument(int selector, int noteId, int note, int noteOffset,
            int noteAtt, int channelAtt, int musChannel, Channel channel)
        {
            int voiceIndex = ChooseVoice(selector);
            HardwareVoice voice = _voices[voiceIndex];
            if (voice.InstrumentSelector != selector) LoadInstrument(voiceIndex, selector, musChannel);
            voice.NoteAttenuation = noteAtt;
            voice.NoteId = noteId;
            voice.PlayingNote = Clamp(note + noteOffset, 0, LastPlayableNote);
            voice.MusChannel = musChannel;
            voice.KeyOnSequence = _nextSequence++;
            SetHardwareVolume(voiceIndex, channelAtt, channel.PanBits);
            int command = BendPitch(voice.PlayingNote, channel.Bend, voice.FineTune) | KeyOn;
            voice.HardwareCommand = command;
            WriteFrequency(voiceIndex, command);
        }

        private void Controller(int musChannel, int controller, int value)
        {
            Channel channel = _channels[musChannel];
            switch (controller)
            {
                case 0: channel.InstrumentIndex = Clamp(value, 0, 127); break;
                case 2:
                    channel.Modulation = Clamp(value >> 2, 0, 7) * 12;
                    if (!channel.UsesModulation) { channel.UsesModulation = true; SwitchToSoftwareVibrato(musChannel); }
                    break;
                case 3:
                    channel.VolumeAttenuation = AttLogSquare[Clamp(value, 0, 127)];
                    UpdateVolume(musChannel); break;
                case 4:
                    channel.PanBits = value <= 64 - PanThreshold ? LeftPan :
                        value >= 64 + PanThreshold ? RightPan : CentrePan;
                    UpdateVolume(musChannel); break;
                case 5:
                    channel.ExpressionAttenuation = AttLogSquare[Clamp(value, 0, 127)];
                    UpdateVolume(musChannel); break;
                case 10: SilenceChannel(musChannel); break;
                case 11: KeyOffChannel(musChannel); break;
                case 12: channel.Mono = true; break;
                case 13: channel.Mono = false; break;
                case 14:
                    channel.VolumeAttenuation = 0; channel.ExpressionAttenuation = 0; channel.PanBits = CentrePan;
                    channel.Bend = 0; channel.Mono = false; UpdateVolume(musChannel); BendChannel(musChannel, 0);
                    break;
            }
        }

        private void KeyOffNote(int musChannel, int note)
        {
            int second = note | 0x100, firstIndex = -1, secondIndex = -1;
            uint firstSequence = uint.MaxValue, secondSequence = uint.MaxValue;
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice v = _voices[i];
                if (v.MusChannel != musChannel) continue;
                if (v.NoteId == note && v.KeyOnSequence < firstSequence) { firstSequence = v.KeyOnSequence; firstIndex = i; }
                if (v.NoteId == second && v.KeyOnSequence < secondSequence) { secondSequence = v.KeyOnSequence; secondIndex = i; }
            }
            if (firstIndex >= 0) KeyOffHardware(firstIndex);
            if (secondIndex >= 0) KeyOffHardware(secondIndex);
        }

        private void KeyOffChannel(int musChannel)
        {
            for (int i = 0; i < VoiceCount; i++) if (_voices[i].MusChannel == musChannel) KeyOffHardware(i);
        }

        private void SilenceChannel(int musChannel)
        {
            for (int i = 0; i < VoiceCount; i++)
            {
                if (_voices[i].MusChannel != musChannel) continue;
                int bank = i >= 9 ? 0x100 : 0, channel = i % 9;
                _chip.WriteRegister(bank | 0x80 | Operator1[channel], 0xFF);
                _chip.WriteRegister(bank | 0x80 | Operator2[channel], 0xFF);
                WriteFrequency(i, _voices[i].HardwareCommand & KeyOffMask);
                _voices[i].InstrumentSelector = -1;
            }
        }

        private void KeyOffHardware(int index)
        {
            HardwareVoice voice = _voices[index];
            if (voice.NoteId < 0) return;
            voice.HardwareCommand &= KeyOffMask;
            WriteFrequency(index, voice.HardwareCommand);
            voice.NoteId = -1;
            voice.ReleaseTime = _musTime;
            voice.KeyOffSequence = _nextSequence++;
        }

        private int ChooseVoice(int selector)
        {
            int oldestOff = -1, oldestIdle = -1, oldestReuse = -1, lowest = 0, lowestChannel = -1;
            uint oldestOffSequence = uint.MaxValue, oldestIdleSequence = uint.MaxValue, oldestReuseSequence = uint.MaxValue;
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice v = _voices[i];
                if (v.MusChannel > lowestChannel && v.MusChannel < 15) { lowestChannel = v.MusChannel; lowest = i; }
                if (v.NoteId >= 0) continue;
                if (v.KeyOffSequence < oldestOffSequence) { oldestOffSequence = v.KeyOffSequence; oldestOff = i; }
                if (_musTime == v.ReleaseTime) continue;
                if (v.KeyOffSequence < oldestIdleSequence) { oldestIdleSequence = v.KeyOffSequence; oldestIdle = i; }
                if (v.KeyOffSequence < oldestReuseSequence && v.InstrumentSelector == selector)
                { oldestReuseSequence = v.KeyOffSequence; oldestReuse = i; }
            }
            if (oldestReuse >= 0) return oldestReuse;
            if (oldestIdle >= 0) return oldestIdle;
            if (oldestOff >= 0) return oldestOff;
            KeyOffHardware(lowest);
            return lowest;
        }

        private void LoadInstrument(int index, int selector, int musChannel)
        {
            HardwareVoice hardware = _voices[index];
            GenMidiInstrument instrument = _bank[selector & 0xFF];
            GenMidiVoice voice = VoiceFor(selector);
            byte mod = voice.ModTremolo, car = voice.CarTremolo;
            hardware.SoftwareVibrato = false;
            if (_channels[musChannel].UsesModulation)
            {
                if ((car & 0x40) != 0) { car &= 0xBF; hardware.SoftwareVibrato = true; }
                if ((voice.Feedback & 1) != 0 && (mod & 0x40) != 0) { mod &= 0xBF; hardware.SoftwareVibrato = true; }
            }
            int bank = index >= 9 ? 0x100 : 0, channel = index % 9;
            _chip.WriteRegister(bank | 0x20 | Operator1[channel], mod);
            _chip.WriteRegister(bank | 0x60 | Operator1[channel], voice.ModAttack);
            _chip.WriteRegister(bank | 0x80 | Operator1[channel], voice.ModSustain);
            _chip.WriteRegister(bank | 0xE0 | Operator1[channel], voice.ModWaveform);
            _chip.WriteRegister(bank | 0x20 | Operator2[channel], car);
            _chip.WriteRegister(bank | 0x60 | Operator2[channel], voice.CarAttack);
            _chip.WriteRegister(bank | 0x80 | Operator2[channel], voice.CarSustain);
            _chip.WriteRegister(bank | 0xE0 | Operator2[channel], voice.CarWaveform);
            hardware.Ksl1 = voice.ModScale; hardware.Ksl2 = voice.CarScale;
            hardware.Level1 = Math.Min(63, (int)voice.ModLevel);
            hardware.Level2 = Math.Min(63, (int)voice.CarLevel);
            hardware.Feedback = voice.Feedback; hardware.FineTune = (selector & 0x100) != 0 ? instrument.FineTuning / 2 - 64 : 0;
            hardware.InstrumentSelector = selector;
        }

        private GenMidiVoice VoiceFor(int selector)
        {
            GenMidiInstrument instrument = _bank[selector & 0xFF];
            return (selector & 0x100) == 0 ? instrument.Voice0 : instrument.Voice1;
        }

        private void SetHardwareVolume(int index, int channelAttenuation, int pan)
        {
            HardwareVoice v = _voices[index];
            int attenuation = Clamp(_mainAttenuation + v.NoteAttenuation + channelAttenuation +
                (pan == CentrePan ? CentreAttenuation : 0), 0, 63);
            int mod = v.Level1, car = Clamp(v.Level2 + attenuation, 0, 63);
            if ((v.Feedback & 1) != 0) mod = Clamp(mod + attenuation, 0, 63);
            int bank = index >= 9 ? 0x100 : 0, channel = index % 9;
            _chip.WriteRegister(bank | 0x40 | Operator1[channel], (byte)(v.Ksl1 | mod));
            _chip.WriteRegister(bank | 0x40 | Operator2[channel], (byte)(v.Ksl2 | car));
            _chip.WriteRegister(bank | 0xC0 | channel, (byte)(v.Feedback | pan));
        }

        private void UpdateVolume(int musChannel)
        {
            Channel c = _channels[musChannel];
            int attenuation = c.VolumeAttenuation + c.ExpressionAttenuation;
            for (int i = 0; i < VoiceCount; i++) if (_voices[i].MusChannel == musChannel) SetHardwareVolume(i, attenuation, c.PanBits);
        }

        private void BendChannel(int musChannel, int bend)
        {
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice v = _voices[i];
                if (v.MusChannel != musChannel || v.NoteId < 0) continue;
                v.HardwareCommand = BendPitch(v.PlayingNote, bend, v.FineTune) | (v.HardwareCommand & KeyOn);
                WriteFrequency(i, v.HardwareCommand);
            }
        }

        private void SwitchToSoftwareVibrato(int musChannel)
        {
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice hw = _voices[i];
                if (hw.MusChannel != musChannel || hw.InstrumentSelector < 0) continue;
                GenMidiVoice v = VoiceFor(hw.InstrumentSelector);
                int bank = i >= 9 ? 0x100 : 0, channel = i % 9;
                hw.SoftwareVibrato = false;
                if ((v.CarTremolo & 0x40) != 0) { _chip.WriteRegister(bank | 0x20 | Operator2[channel], (byte)(v.CarTremolo & 0xBF)); hw.SoftwareVibrato = true; }
                if ((v.Feedback & 1) != 0 && (v.ModTremolo & 0x40) != 0) { _chip.WriteRegister(bank | 0x20 | Operator1[channel], (byte)(v.ModTremolo & 0xBF)); hw.SoftwareVibrato = true; }
            }
        }

        private void DoLfo()
        {
            if ((_musTime & 1) != 0) return;
            _lfoOffset = (_lfoOffset + 1) % 12;
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice v = _voices[i];
                if (!v.SoftwareVibrato || v.MusChannel >= 16) continue;
                Channel channel = _channels[v.MusChannel];
                int bend = channel.Bend + LfoTable[channel.Modulation + _lfoOffset];
                v.HardwareCommand = BendPitch(v.PlayingNote, bend, v.FineTune) | (v.HardwareCommand & KeyOn);
                WriteFrequency(i, v.HardwareCommand);
            }
        }

        private static int BendPitch(int note, int bend, int fineTune)
        {
            note = Clamp(note, 0, LastPlayableNote);
            if (bend == 0 && fineTune == 0) return NoteCommands[note] & KeyOffMask;
            int direction = bend < 0 ? -1 : 1, magnitude = Math.Abs(bend);
            while (magnitude >= 64 && note + direction >= 0 && note + direction <= LastPlayableNote)
            { magnitude -= 64; note += direction; }
            int current = NoteCommands[note], scale = (current >> 10) & 7;
            int frequency = ((current & 1023) + fineTune) << scale;
            if (magnitude > 0)
            {
                int nextNote = Clamp(note + direction, 0, LastPlayableNote);
                int next = NoteCommands[nextNote], nextScale = (next >> 10) & 7;
                int nextFrequency = ((next & 1023) + fineTune) << nextScale;
                frequency += (nextFrequency - frequency) * magnitude >> 6;
                scale = Math.Max(scale, nextScale);
            }
            while (scale < 7 && frequency >= (1024 << scale)) scale++;
            return (scale << 10) | (frequency >> scale);
        }

        private void WriteFrequency(int index, int command)
        {
            int bank = index >= 9 ? 0x100 : 0, channel = index % 9;
            _chip.WriteRegister(bank | 0xA0 | channel, (byte)command);
            _chip.WriteRegister(bank | 0xB0 | channel, (byte)(command >> 8));
        }

        private void ResetSequencerState()
        {
            for (int i = 0; i < 16; i++)
            {
                Channel c = _channels[i];
                c.Mono = false; c.LastVolume = 0; c.VolumeAttenuation = 0; c.ExpressionAttenuation = 0;
                c.Bend = 0; c.PanBits = CentrePan; c.Modulation = 0; c.UsesModulation = false; c.InstrumentIndex = 0;
            }
            for (int i = 0; i < VoiceCount; i++)
            {
                HardwareVoice v = _voices[i];
                v.NoteId = -1; v.MusChannel = -1; v.InstrumentSelector = -1; v.SoftwareVibrato = false;
                v.KeyOnSequence = 0; v.KeyOffSequence = 0; v.ReleaseTime = 0; v.HardwareCommand = 0;
            }
        }

        private void InitializeChip()
        {
            _chip.WriteRegister(0x01, 0); _chip.WriteRegister(0x04, 0); _chip.WriteRegister(0x08, 0);
            _chip.WriteRegister(0x01, 0x20); _chip.WriteRegister(0x105, 1); _chip.WriteRegister(0x104, 0); _chip.WriteRegister(0xBD, 0);
            for (int bank = 0; bank <= 0x100; bank += 0x100)
            for (int ch = 0; ch < 9; ch++)
            {
                _chip.WriteRegister(bank | 0x80 | Operator2[ch], 0xFF); _chip.WriteRegister(bank | 0x80 | Operator1[ch], 0xFF);
                _chip.WriteRegister(bank | 0xB0 | ch, 0); _chip.WriteRegister(bank | 0xA0 | ch, 0);
                _chip.WriteRegister(bank | 0x20 | Operator2[ch], 0); _chip.WriteRegister(bank | 0x20 | Operator1[ch], 0);
                _chip.WriteRegister(bank | 0x60 | Operator2[ch], 0); _chip.WriteRegister(bank | 0x60 | Operator1[ch], 0);
                _chip.WriteRegister(bank | 0xC0 | ch, 0); _chip.WriteRegister(bank | 0xE0 | Operator2[ch], 0); _chip.WriteRegister(bank | 0xE0 | Operator1[ch], 0);
                _chip.WriteRegister(bank | 0x40 | Operator2[ch], 63); _chip.WriteRegister(bank | 0x40 | Operator1[ch], 63);
            }
        }

        private static int Clamp(int value, int min, int max) => value < min ? min : value > max ? max : value;

        private sealed class Channel
        {
            public bool Mono; public byte LastVolume; public int VolumeAttenuation; public int ExpressionAttenuation;
            public int Bend; public int PanBits; public int Modulation; public bool UsesModulation; public int InstrumentIndex;
        }

        private sealed class HardwareVoice
        {
            public uint KeyOnSequence, KeyOffSequence, ReleaseTime; public int NoteId, NoteAttenuation, HardwareCommand;
            public int PlayingNote, MusChannel, InstrumentSelector, Ksl1, Ksl2, Level1, Level2, Feedback, FineTune;
            public bool SoftwareVibrato;
        }
    }
}
