using System.Collections.Generic;
using System.Globalization;
using System.IO;
using NUnit.Framework;
using UnityEngine;
using Doom.Graphics;
using Doom.MapBuild;
using Doom.Things;
using Doom.Wad;

namespace Doom.Map.Tests
{
    /// The Enhanced fireball is generated by Tools/make_fireball_mesh.py and
    /// then trusted blindly by the runtime: the ball is scaled straight to the
    /// patch width with no bounds measuring, and the shader treats object space
    /// as a unit sphere. Both only hold while the OBJ stays centred and
    /// normalized, so pin the generator's contract here — and pin the asset
    /// chain OBJ -> MTL -> texture, the failure that shipped white POSS
    /// corpses (2026-08-16) with every other test still green.
    public class FireballAssetTests
    {
        const int ImpDoomEdNum = 3001;

        static string AssetDir() => Path.Combine(
            Application.dataPath, "Resources", "ExperimentalProjectiles", "BAL1");

        static string WadPath() => Path.Combine(
            Application.streamingAssetsPath, "wads", "freedoom1.wad");

        static MonsterDef Imp()
        {
            Assert.That(MonsterTable.TryGet(ImpDoomEdNum, out var def), Is.True);
            return def;
        }

        [Test]
        public void Ball_resolves_its_material_and_profile_texture()
        {
            string dir = AssetDir();
            string obj = Path.Combine(dir, "BAL1.obj");
            Assert.That(File.Exists(obj), Is.True, "BAL1.obj missing");

            string mtlRef = null;
            foreach (string line in File.ReadLines(obj))
            {
                if (!line.StartsWith("mtllib ")) continue;
                mtlRef = line.Substring(7).Trim();
                break;
            }
            Assert.That(mtlRef, Is.EqualTo("BAL1.mtl"),
                "a dangling mtllib imports the ball with Unity's default material");

            string mtl = Path.Combine(dir, mtlRef);
            Assert.That(File.Exists(mtl), Is.True, $"{mtlRef} missing");

            string mapRef = null;
            foreach (string line in File.ReadLines(mtl))
            {
                if (!line.StartsWith("map_Kd ")) continue;
                mapRef = line.Substring(7).Trim();
                break;
            }
            Assert.That(mapRef, Is.EqualTo("BAL1A0_profile.png"));
            Assert.That(File.Exists(Path.Combine(dir, mapRef)), Is.True,
                $"{mapRef} missing");
        }

        [Test]
        public void Every_fly_frame_has_its_own_colour_table()
        {
            var def = Imp();
            Assert.That(ExperimentalProjectileModel.IsRoutedForTest(def.MissileSprite),
                Is.True, "the routed sprite must be the one the imp actually fires");

            string dir = AssetDir();
            foreach (int frame in def.MissileFlyFrames)
            {
                string lump = def.MissileSprite + (char)('A' + frame) + "0";
                Assert.That(File.Exists(Path.Combine(dir, lump + "_profile.png")),
                    Is.True,
                    $"{lump}_profile.png missing — coverage is all-or-nothing, a " +
                    "gap would swap styles mid-flight");
            }
        }

        [Test]
        public void Explosion_frames_stay_off_the_mesh_path()
        {
            var def = Imp();
            string dir = AssetDir();
            foreach (int frame in def.MissileExplodeFrames)
            {
                string lump = def.MissileSprite + (char)('A' + frame) + "0";
                Assert.That(File.Exists(Path.Combine(dir, lump + "_profile.png")),
                    Is.False,
                    $"{lump} is a spray of loose pixels — it belongs to the " +
                    "billboard, and a table for it would suggest otherwise");
            }
        }

        [Test]
        public void Ball_is_centred_and_normalized_to_a_unit_diameter()
        {
            var verts = ReadVertices(Path.Combine(AssetDir(), "BAL1.obj"));
            Assert.That(verts.Count, Is.GreaterThan(0), "BAL1.obj has no vertices");

            var min = new Vector3(float.MaxValue, float.MaxValue, float.MaxValue);
            var max = new Vector3(float.MinValue, float.MinValue, float.MinValue);
            foreach (var v in verts) { min = Vector3.Min(min, v); max = Vector3.Max(max, v); }

            // The runtime sets localScale = patch width and never measures the
            // mesh, and the shader divides object-space radii by 0.5.
            Assert.That(Mathf.Max(max.x, max.y, max.z), Is.EqualTo(0.5f).Within(0.001f),
                "the ball must reach exactly 0.5 in object space");
            Assert.That(Mathf.Min(min.x, min.y, min.z), Is.EqualTo(-0.5f).Within(0.001f));
            Vector3 center = (min + max) * 0.5f;
            Assert.That(center.magnitude, Is.LessThan(0.001f),
                "the ball must be centred on the object origin — the shader " +
                "measures the radial coordinate from there");
        }

        [Test]
        public void Uvs_carry_only_the_variant_row()
        {
            var uvs = ReadUvs(Path.Combine(AssetDir(), "BAL1.obj"));
            Assert.That(uvs.Count, Is.GreaterThan(0), "BAL1.obj has no UVs");

            var rows = new HashSet<float>();
            foreach (var uv in uvs)
            {
                // U is the radial coordinate and the shader computes it from
                // the view; baking anything but a placeholder here would be a
                // silent contradiction.
                Assert.That(uv.x, Is.EqualTo(0.5f).Within(0.0001f));
                Assert.That(uv.y, Is.GreaterThan(0f).And.LessThan(1f));
                rows.Add(uv.y);
            }
            Assert.That(rows.Count, Is.GreaterThan(1),
                "voxels must spread across the table's variant rows, or the " +
                "ball reads as a smooth ramp instead of the sprite's boiling");
        }

        [Test]
        public void Fly_sprite_is_the_round_patch_the_ball_assumes()
        {
            string path = WadPath();
            if (!File.Exists(path)) Assert.Ignore("freedoom1.wad missing");
            using var wad = WadFile.Open(path);

            var def = Imp();
            foreach (int frame in def.MissileFlyFrames)
            {
                string lump = def.MissileSprite + (char)('A' + frame) + "0";
                Assert.That(wad.FindLump(lump), Is.GreaterThanOrEqualTo(0),
                    $"{lump} must exist in freedoom1.wad");
                var header = Patch.ReadHeader(wad.ReadLump(lump));
                Assert.That(header.Width, Is.EqualTo(header.Height),
                    $"{lump} is not square — a ball scaled by the patch width " +
                    "would no longer cover the sprite it replaces");
            }
        }

        static List<Vector3> ReadVertices(string obj)
        {
            var result = new List<Vector3>();
            foreach (string line in File.ReadLines(obj))
            {
                if (!line.StartsWith("v ")) continue;
                string[] p = line.Split(' ');
                result.Add(new Vector3(Num(p[1]), Num(p[2]), Num(p[3])));
            }
            return result;
        }

        static List<Vector2> ReadUvs(string obj)
        {
            var result = new List<Vector2>();
            foreach (string line in File.ReadLines(obj))
            {
                if (!line.StartsWith("vt ")) continue;
                string[] p = line.Split(' ');
                result.Add(new Vector2(Num(p[1]), Num(p[2])));
            }
            return result;
        }

        static float Num(string s) =>
            float.Parse(s, CultureInfo.InvariantCulture);
    }
}
